"""Domain result models for inventory reconciliation."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

import pandas as pd


class ReconciliationStatus(str, Enum):
    """User-facing outcomes for one material requirement."""

    COVERED = "CUBIERTO"
    PARTIAL_COVERAGE = "COBERTURA_PARCIAL"
    OUT_OF_STOCK = "SIN_EXISTENCIA"
    REVIEW_REQUIRED = "REVISION_REQUERIDA"
    NO_MATCH = "SIN_COINCIDENCIA"
    UNSEGMENTED = "NO_SEGMENTADO"


@dataclass(frozen=True, slots=True)
class ReconciliationReport:
    """Tables generated by one complete segmentation and matching run."""

    matches: pd.DataFrame
    requirements: pd.DataFrame
    inventory: pd.DataFrame

    @property
    def requirement_count(self) -> int:
        """Return the number of processed requirement rows."""
        return len(self.matches)

    @property
    def covered_count(self) -> int:
        """Return requirements covered in full by exact inventory matches."""
        if self.matches.empty:
            return 0
        return int(
            (
                self.matches["estado"]
                == ReconciliationStatus.COVERED.value
            ).sum()
        )

    @property
    def review_count(self) -> int:
        """Return requirements that need human review."""
        if self.matches.empty:
            return 0
        review_statuses = {
            ReconciliationStatus.REVIEW_REQUIRED.value,
            ReconciliationStatus.UNSEGMENTED.value,
        }
        return int(self.matches["estado"].isin(review_statuses).sum())

    def build_summary(self) -> str:
        """Build a concise summary suitable for the desktop interface."""
        assigned = (
            float(self.matches["cantidad_asignada"].sum())
            if not self.matches.empty
            else 0.0
        )
        required = (
            float(self.matches["cantidad_requerida"].sum())
            if not self.matches.empty
            else 0.0
        )
        coverage = 0.0 if required == 0 else assigned / required * 100
        return (
            f"{self.requirement_count} requerimientos procesados; "
            f"{self.covered_count} cubiertos; "
            f"{self.review_count} requieren revision; "
            f"cobertura total {coverage:.1f}%."
        )
